database:
  replicas: 1
  instanceProfile:
    cpu: "500m"
    memory: "0.5Gi"

controller:
  env:
    SIMPLYBLOCK_CSI_NAMESPACE: 'simplyblock-csi'
    VELA_ENABLE_DB_EXTERNAL_IPV6_LOADBALANCER: 'false'
