database:
  replicas: 1
  cpu: "500m"
  memory: "0.5Gi"

controller:
  env:
    VELA_SIMPLYBLOCK_CSI_NAMESPACE: 'simplyblock-csi'
    VELA_ENABLE_DB_EXTERNAL_IPV6_LOADBALANCER: 'false'

studio:
  image:
    tag: dev
