[checks]
positive_data_acceptance.expected-statuses = [200, 201, 204, 404, 409]

# Disable until upstream fix for renamed resources is deployed
[[operations]]
include-name = [
    "PUT /organizations/{organization_id}/",
    "PUT /organizations/{organization_id}/projects/{project_id}",
]
checks.enabled = false

# not sure how to mock these
[[operations]]
include-name = [
    "POST /users/",
    "POST /users/{user_ref}/",
]
checks.enabled = false
