[checks]
positive_data_acceptance.expected-statuses = [200, 201, 204, 404, 409]

# Disable until upstream fix for renamed resources is deployed
[[operations]]
include-name = [
    "PUT /organizations/{organization_slug}/",
    "PUT /organizations/{organization_slug}/projects/{project_id}",
]
checks.enabled = false

# schemathesis can't cope with the sluggable constraint
[[operations]]
include-name = [
    "POST /organizations/",
    "POST /organizations/{organization_slug}/projects/",
]
checks.positive_data_acceptance.expected-statuses = [201, 404, 409, 422]

# not sure how to mock these
[[operations]]
include-name = [
    "POST /users/",
    "POST /users/{user_ref}/",
]
checks.enabled = false
