[checks]
positive_data_acceptance.expected-statuses = [200, 201, 204, 404, 409]

# not sure how to mock these
[[operations]]
include-name = [
    "POST /users/",
    "POST /users/{user_ref}/",
]
checks.enabled = false
