apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-tls" (include "vela.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
spec:
  secretName: "db-tls-secret"
  issuerRef:
    name: "letsencrypt-dns"
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - {{ .Values.autoscalerVm.tls.serverName | quote }}
