{{- if and .Values.autoscalerVm.enabled .Values.pgbouncer.enabled }}
{{- $pgbouncerName := printf "%s-pgbouncer" (include "vela.fullname" .) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $pgbouncerName }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pgbouncer.service.type }}
  ports:
    - port: {{ .Values.pgbouncer.service.port }}
      targetPort: 6432
      protocol: TCP
      name: pgbouncer
  selector:
{{ include "vela.autoscaler.selectorLabel" . | nindent 4 }}
{{- end }}
