{{- if not .Values.secret.db.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.db" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  pgmeta_crypto_key: {{ .Values.secret.pgmeta_crypto_key }}
{{- range $key, $value := .Values.secret.db }}
{{- if $value }}
{{- if or (eq (typeOf $value) "string") (eq (typeOf $value) "numeric") }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
  password_encoded: {{ .Values.secret.db.password | urlquery | b64enc }}
{{- range $key, $value := .Values.db.credentials }}
{{- if $value }}
{{- if or (eq (typeOf $value) "string") (eq (typeOf $value) "numeric") }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
