apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-tls-secret
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: {{ .Values.issuer }}
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "{{ .Values.domain }}"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vela-auth-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-tls-auth-secret
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: {{ .Values.issuer }}
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: vela-auth-service.{{ .Release.Namespace }}.svc.cluster.local
  dnsNames:
    - vela-auth-service.{{ .Release.Namespace }}.svc.cluster.local
