---
apiVersion: v1
kind: Secret
metadata:
  name: vela-grafana-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  VELA_GRAFANA_SECURITY_ADMIN_USER: "{{ .Values.monitoring.VELA_GRAFANA_SECURITY_ADMIN_USER }}"
  VELA_GRAFANA_SECURITY_ADMIN_PASSWORD: "{{ .Values.monitoring.VELA_GRAFANA_SECURITY_ADMIN_PASSWORD }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vela-grafana-datasource
  labels:
    app: vela-grafana
  namespace: {{ .Release.Namespace }}
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://{{ .Values.prometheus.name }}.{{ .Values.prometheus.namespace }}.svc.cluster.local:9090
      isDefault: true
      access: proxy
      uid: PBFA97CFB590B2093
      editable: true      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vela-grafana
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vela-grafana
  template:
    metadata:
      labels:
        app: vela-grafana
    spec:      
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: vela-grafana-secret
                  key: VELA_GRAFANA_SECURITY_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vela-grafana-secret
                  key: VELA_GRAFANA_SECURITY_ADMIN_PASSWORD
            - name: GF_ALERTING_ENABLED
              value: "true"
            - name: GF_PATHS_PROVISIONING
              value: "/etc/grafana/provisioning"
            - name: GF_SERVER_ROOT_URL
              value: "http://localhost/grafana"
            - name: GF_AUTH_JWT_ENABLED
              value: "true"
            - name: "GF_AUTH_JWT_HEADER_NAME"
              value: "Authorization"
            - name: "GF_AUTH_JWT_USERNAME_CLAIM" 
              value: "sub"
            - name: "GF_AUTH_JWT_EMAIL_CLAIM"
              value: "email"
            - name: "GF_AUTH_JWT_AUTO_SIGN_UP" 
              value: "true"
            - name: "GF_USERS_ALLOW_SIGN_UP"
              value: "false"
            - name: "GF_AUTH_JWT_JWK_SET_URL" 
              value: "https://{{ .Values.domain }}:30808/auth/realms/vela/protocol/openid-connect/certs"
          volumeMounts:
            - name: datasource-config
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: datasource-config
          configMap:
            name: vela-grafana-datasource
        - name: grafana-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: vela-grafana
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: vela-grafana
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
