---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: vela-public-gateway 
  # using shared model. keeping this in kong-system namespace so that it can shared by all `HTTPRoute` objects across namespaces
  namespace: kong-system
spec:
  gatewayClassName: kong-class # installed by admin
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: "*.{{ .Values.domain }}"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.domaincertsecret }}
      allowedRoutes:
        namespaces:
          from: All
