{{- if and .Values.vector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vela-vector
  labels:
    app.kubernetes.io/name: vela
    app.kubernetes.io/instance: vela
    vector.dev/exclude: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vela-vector-reader-{{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    resourceNames:
      - vela-*
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vela-vector-view-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: vela-vector
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: vela-vector-reader-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
