{{- if not .Values.secret.analytics.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vela.secret.analytics" . }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secret.analytics }}
{{- if $value }}
{{- if eq (typeOf $value) "string" }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
  namespace: {{ .Release.Namespace | b64enc }}
  branch: {{ trimPrefix "vela-" .Release.Namespace | b64enc }}
{{- end }}
