apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vela.secret.analytics" . }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
type: Opaque
data:
  namespace: {{ .Release.Namespace | b64enc }}
  branch: {{ trimPrefix "vela-" .Release.Namespace | b64enc }}
