apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vela.secret.db" . }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
type: Opaque
data:
  password_encoded: {{ .Values.secret.db.password | urlquery | b64enc }}
stringData:
  pgmeta_crypto_key: {{ .Values.secret.pgmeta_crypto_key | default "" | quote }}
  password: {{ .Values.secret.db.password | default "" | quote }}
  pgbouncer_admin_password: {{ .Values.secret.pgbouncer.admin_password | default "" | quote }}
