{{- if .Values.secret.jwt }}
{{- if not .Values.secret.jwt.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vela.secret.jwt" . }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secret.jwt }}
{{- if $value }}
{{- if eq (typeOf $value) "string" }}
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
