services:
  vela:
    build:
      context: ..
      dockerfile: containers/Containerfile
    ports:
      - "8000:8000"
    depends_on:
      - fdb
    volumes:
      - ..:/app
      - fdb-config:/etc/foundationdb
    command: 'bash -c "python -m venv /tmp/venv && source /tmp/venv/bin/activate && pip install -e . && uvicorn --host 0.0.0.0 --reload simplyblock.vela:app"'
    restart: unless-stopped

  fdb:
    image: docker.io/foundationdb/foundationdb:7.3.69
    ports:
      - "4500:4500"
    environment:
      FDB_NETWORKING_MODE: container
      FDB_CLUSTER_FILE: '/etc/foundationdb/fdb.cluster'
      FDB_CLUSTER_FILE_CONTENTS: 'docker:docker@fdb:4500'
    volumes:
      - fdb-config:/etc/foundationdb
    restart: unless-stopped
    post_start:
      - command: fdbcli --exec 'configure new single ssd'
        user: root

volumes:
  fdb-config:
