services:
  reverse-proxy:
    image: docker.io/haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 8000:8000
    depends_on:
      vela:
        condition: service_healthy
      auth:
        condition: service_healthy
    restart: unless-stopped


  vela:
    build:
      context: ..
      dockerfile: containers/Containerfile
    volumes:
      - ~/.kube/config:/root/.kube/config:ro
    environment:
      VELA_POSTGRES_URL: 'postgresql+asyncpg://postgres:vela@database:5432/vela'
      VELA_JWT_SECRET: 'secret'
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:8000/health']
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped


  auth:
    image: supabase/gotrue:v2.177.0
    environment:
      API_EXTERNAL_URL: 'http://localhost:8081/'
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_SITE_URL: 'http://localhost:8081/'

      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: 'postgresql://supabase_auth_admin:root@database:5432/vela'

      GOTRUE_JWT_SECRET: 'secret'
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:8081/health']
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped


  database:
    image: docker.io/postgres:17
    environment:
      POSTGRES_PASSWORD: vela
      POSTGRES_DB: vela
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/90-init.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d vela']
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped
