services:
  reverse-proxy:
    image: docker.io/haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 8000:8000
    depends_on:
      vela:
        condition: service_healthy
      auth:
        condition: service_healthy
    restart: unless-stopped


  vela:
    build:
      context: ..
      dockerfile: containers/Containerfile
    volumes:
      - ~/.kube/config:/root/.kube/config:ro
    environment:
      VELA_ROOT_PATH: '/vela'
      VELA_JWT_SECRET: 'http://auth:8080/auth/realms/vela/protocol/openid-connect/certs'
      VELA_POSTGRES_URL: 'postgresql+asyncpg://postgres:vela@database:5432/vela'
      VELA_CORS_ORIGINS: '["http://localhost:3000"]'
      VELA_PGMETA_CRYPTO_KEY: 'secret'
      # VELA_SENTRY_DSN: 'https://examplePublicKey@o0.ingest.sentry.io/0'
      # VELA_SENTRY_ENVIRONMENT: 'local'
      # VELA_SENTRY_TRACES_SAMPLE_RATE: '0.1'
      # VELA_SENTRY_PROFILES_SAMPLE_RATE: '0.1'
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:8000/health']
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped


  auth:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_PROXY: edge
      KC_HOSTNAME: http://localhost:8000/auth
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HEALTH_ENABLED: 'true'
    command: start-dev --import-realm --verbose
    volumes:
    - ./realm.json:/opt/keycloak/data/import/vela-realm.json:ro
    healthcheck:
      test: ["CMD-SHELL", "timeout 10 bash -c '</dev/tcp/localhost/8080' || exit 1"]  # This should do a proper request, but the container doesn't ship curl, wget, or telnet and using bash builtins is nasty
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      database:
        condition: service_healthy


  database:
    image: docker.io/postgres:17
    environment:
      POSTGRES_PASSWORD: vela
      POSTGRES_DB: vela
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/90-init.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d vela']
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped
