services:
  reverse-proxy:
    image: docker.io/haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 8000:8000
    depends_on:
      vela:
        condition: service_healthy
      auth:
        condition: service_healthy
    restart: unless-stopped


  vela:
    build:
      context: ..
      dockerfile: containers/Containerfile
    volumes:
      - ~/.kube/config:/root/.kube/config:ro
      - ..:/app
    command: 'bash -c "python -m venv /tmp/venv && source /tmp/venv/bin/activate && pip install -e . && uvicorn --host 0.0.0.0 --reload simplyblock.vela.api:app"'
    environment:
      VELA_ROOT_PATH: '/vela'
      VELA_JWT_SECRET: 'http://auth:8080/auth/realms/vela/protocol/openid-connect/certs'
      VELA_POSTGRES_URL: 'postgresql+asyncpg://postgres:vela@database:5432/vela'
      VELA_CORS_ORIGINS: '["http://localhost:3000"]'
      VELA_PGMETA_CRYPTO_KEY: 'secret'
      VELA_KEYCLOAK_URL: 'http://auth:8080/auth/'
      VELA_KEYCLOAK_ADMIN_NAME: 'admin'
      VELA_KEYCLOAK_ADMIN_SECRET: 'admin'
      VELA_CLOUDFLARE_API_TOKEN: 'your_cloudflare_api_token'
      VELA_CLOUDFLARE_ZONE_ID: 'your_cloudflare_zone_id'
      VELA_CLOUDFLARE_BRANCH_REF_CNAME: 'branch-ref.staging.vela.run'
      VELA_CLOUDFLARE_DOMAIN_SUFFIX: 'example.com'
      VELA_DEPLOYMENT_NAMESPACE_PREFIX: 'vela'
      LOGFLARE_PUBLIC_ACCESS_TOKEN: 'my-super-secret-api-key'

    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:8000/health']
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped


  auth:
    image: quay.io/keycloak/keycloak:26.4
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_PROXY: edge
      KC_HOSTNAME: http://localhost:8000/auth
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HEALTH_ENABLED: 'true'
    command: start-dev --import-realm --verbose
    volumes:
    - ./realm.json:/opt/keycloak/data/import/vela-realm.json:ro
    healthcheck:
      test: ["CMD-SHELL", "timeout 10 bash -c '</dev/tcp/localhost/8080' || exit 1"]  # This should do a proper request, but the container doesn't ship curl, wget, or telnet and using bash builtins is nasty
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      database:
        condition: service_healthy


  database:
    image: docker.io/postgres:17
    environment:
      POSTGRES_PASSWORD: vela
      POSTGRES_DB: vela
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/90-init.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d vela']
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped
