services:
  vela:
    build:
      context: ..
      dockerfile: containers/Containerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ..:/app
    environment:
      POSTGRES_URL: 'postgresql://vela:vela@db:5432/vela'
    command: 'bash -c "python -m venv /tmp/venv && source /tmp/venv/bin/activate && pip install -e . && uvicorn --host 0.0.0.0 --reload simplyblock.vela:app"'
    restart: unless-stopped

  db:
    image: docker.io/postgres:17
    environment:
      POSTGRES_USER: vela
      POSTGRES_PASSWORD: vela
      POSTGRES_DATABASE: vela
    restart: unless-stopped
