services:
  vela:
    build:
      context: ..
      dockerfile: containers/Containerfile
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
      auth:
        condition: service_healthy
    volumes:
      - ..:/app
    environment:
      VELA_POSTGRES_URL: 'postgresql+asyncpg://postgres:vela@database:5432/vela'
      VELA_JWT_SECRET: 'secret'
    command: 'bash -c "python -m venv /tmp/venv && source /tmp/venv/bin/activate && pip install -e . && uvicorn --host 0.0.0.0 --reload simplyblock.vela:app"'
    restart: unless-stopped


  auth:
    image: supabase/gotrue:v2.177.0
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:9999/health"
        ]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      database:
        condition: service_healthy
    environment:
      API_EXTERNAL_URL: 'http://localhost:9999/'
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_SITE_URL: 'http://localhost:9999/'

      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: 'postgresql://supabase_auth_admin:root@database:5432/vela'

      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_SECRET: 'secret'


  database:
    image: docker.io/postgres:17
    environment:
      POSTGRES_PASSWORD: vela
      POSTGRES_DB: vela
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/90-init.sql:Z
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d vela']
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_JWT_ENABLED=true
      - GF_AUTH_JWT_HEADER_NAME=Authorization
      - GF_AUTH_JWT_AUTO_SIGN_UP=true
      - GF_AUTH_JWT_USERNAME_CLAIM=user
      - GF_AUTH_JWT_EMAIL_CLAIM=email
      - GF_AUTH_JWT_JWK_SET_URL=https://caddy:8443/jwks.json
      - GF_AUTH_JWT_ALLOW_INSECURE_CERTIFICATE=true
      - GF_AUTH_JWT_TLS_SKIP_VERIFY_INSECURE=true
    volumes:
      - ./jwks/public.key:/etc/grafana/public-key.pem:ro
    depends_on:
      - caddy

  jwks-server:
    image: python:3.9-slim
    container_name: jwks-server
    working_dir: /jwks
    command: python3 -m http.server 8080
    volumes:
      - ./jwks:/jwks:ro

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "8443:8443"
    volumes:
      - ./jwks:/srv:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
