services:
  vela:
    build:
      context: ..
      dockerfile: containers/Containerfile
    ports:
      - "8000:8000"
    depends_on:
      - fdb
    volumes:
      - fdb-config:/etc/foundationdb
    restart: unless-stopped

  fdb:
    image: docker.io/foundationdb/foundationdb:7.3.69
    ports:
      - "4500:4500"
      - "4501:4501"
    environment:
      FDB_NETWORKING_MODE: container
      FDB_CLUSTER_FILE: '/etc/foundationdb/fdb.cluster'
      FDB_CLUSTER_FILE_CONTENTS: 'docker:docker@fdb:4500'
    volumes:
      - fdb-config:/etc/foundationdb
      - fdb-data:/var/fdb/data
    restart: unless-stopped
    post_start:
      - command: fdbcli --exec 'configure new single ssd'
        user: root

volumes:
  fdb-config:
  fdb-data:
