{{- if and .Values.meta.enabled .Values.meta.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vela.meta.serviceAccountName" . }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
    app.kubernetes.io/component: meta
  {{- with .Values.meta.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
