{{- if .Values.meta.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vela.meta.fullname" . }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
    app.kubernetes.io/component: meta
spec:
  type: {{ .Values.meta.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.meta.service.port | default 8080 }}
      targetPort: {{ .Values.meta.service.port | default 8080 }}
      protocol: TCP
  selector:
    {{- include "vela.meta.selectorLabels" . | nindent 4 }}
{{- end }}
