# File structure of values.yaml:
# |-- 1.  Database
# |-- 2.  Rest
# |-- 3.  Meta
# |-- 4.  Storage API

# docker-compose payload injected via helm --set-file composeYaml
composeYaml: ""
vectorYaml: ""
pgHbaConf: ""

secret:
  # jwt will be used to reference secret in multiple services:
  # Anon & Service key: Studio, Storage, Kong
  # JWT Secret: Analytics, Auth, Rest, Storage
  pgmeta_crypto_key: ''
  jwt:
    anonKey: ""
    serviceKey: ""
    secret: ""
  # database credentials
  # these fields must be provided even if using external database
  db:
    password: ""
  pgbouncer:
    admin_password: "pgadmin_pwd" # TODO: auto generate this in the next PR.
  # analytics Logflare API key
  analytics:
    apiKey: your-super-secret-and-long-logflare-key
    # specify existing secret, which takes precedence over variable above
    secretRef: ""
    # override secret keys for existing secret refs
    secretRefKey:
      apiKey: apiKey

# A standalone Postgres database configured to work with vela services.
db:
  # Enable database provisioning
  enabled: true
  image:
    repository: supabase/postgres
    pullPolicy: IfNotPresent
    tag: "15.1.0.147"
  imagePullSecrets: []
  replicaCount: 1
  nameOverride: ""
  fullnameOverride: ""
  livenessProbe:
    exec:
      command:
        - pg_isready
        - -U
        - postgres
    initialDelaySeconds: 3
  readinessProbe: {}
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    externalEnabled: false
    type: LoadBalancer
    port: 5432
    ipFamilies:
      - IPv6
    ipFamilyPolicy: "SingleStack"
    clusterIP:
      ipFamilies:
        - IPv4
      ipFamilyPolicy: "SingleStack"
  environment:
    POSTGRES_HOST: /var/run/postgresql
    PGPORT: "5432"
    POSTGRES_PORT: "5432"
    JWT_EXP: 3600
  resources: # Placeholder values. Actual values are filled by create_vela_config
    guestMemory: 1G
    limits:
      cpu: 100m
    requests:
      cpu: 100m
  persistence:
    enabled: true
    create: true
    storageClassName: "simplyblock-csi-sc"
    annotations: {}
    size: 10Gi
    accessModes:
      - ReadWriteMany
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # Additional migration scripts can be defined here
  config: {}

# Neon autoscaler VM
autoscalerVm:
  enabled: false
  nameOverride: ""
  fullnameOverride: ""
  powerState: Running
  extraNetwork:
    enable: true
  image:
    repository: docker.io/manoharbrm/vela-vm
    tag: latest
  mountPath: /var/lib/postgresql
  resources: # Placeholder values. Actual values are filled by create_vela_config
    cpus:
      min: "1m"
      use: "1m"
      max: "64000m"
    memorySlots:
      min: 0
      use: 0
      max: 0
      limit: 0
    memorySlotSize: 128Mi
  persistence:
    storageClassName: "simplyblock-csi-sc"
    size: 20Gi
    accessModes:
      - ReadWriteMany

# PgBouncer connection pooler
pgbouncer:
  enabled: true
  replicaCount: 1
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: docker.io/edoburu/pgbouncer
    pullPolicy: IfNotPresent
    tag: "v1.24.1-p0"
  imagePullSecrets: []
  service:
    type: ClusterIP
    port: 6432
  resources:
    limits:
      cpu: 250m
      memory: 250Mi
    requests:
      cpu: 250m
      memory: 250Mi
  config:
    max_client_conn: 100
    default_pool_size: 20
    reserve_pool_size: 0
    query_wait_timeout: 30
    server_idle_timeout: 60
    server_lifetime: 600
  authUser: postgres
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Rest Service
rest:
  # Enable postgrest provisioning
  enabled: false
  image:
    repository: postgrest/postgrest
    pullPolicy: IfNotPresent
    tag: v12.0.1
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  livenessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 3
  readinessProbe: {}
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    type: ClusterIP
    port: 3000
  environment:
    # Override the database hostname if using external database
    # DB_HOST: DATABASE.NAMESPACE.svc.cluster.local
    DB_USER: authenticator
    DB_PORT: 5432
    DB_DRIVER: postgres
    DB_SSL: disable  # disable, allow, prefer, require, verify-ca, verify-full
    PGRST_DB_SCHEMAS: public,storage,graphql_public
    PGRST_DB_ANON_ROLE: anon
    PGRST_DB_USE_LEGACY_GUCS: false
    PGRST_APP_SETTINGS_JWT_EXP: 3600
  # volumeMounts:
  #   - name: volume_name
  #     mountPath: /path/to/my/secret
  # volumes:
  #   - name: volume_name
  #     secret:
  #       defaultMode: 733
  #       secretName: my_secret
  #       items:
  #       - key: my_secret.txt
  #         path: name_of_file_in_container.txt
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Meta Service
meta:
  # Enable meta provisioning
  enabled: false
  image:
    repository: supabase/postgres-meta
    pullPolicy: IfNotPresent
    tag: v0.80.0
  imagePullSecrets: []
  replicaCount: 1
  nameOverride: ""
  fullnameOverride: ""
  livenessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 3
  readinessProbe: {}
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    type: ClusterIP
    port: 8080
  environment:
    # Override the database hostname if using external database
    # DB_HOST: DATABASE.NAMESPACE.svc.cluster.local
    DB_USER: supabase_admin
    DB_PORT: 5432
    DB_DRIVER: postgres
    DB_SSL: disable  # disable, allow, prefer, require, verify-ca, verify-full
    PG_META_PORT: "8080"
  # volumeMounts:
  #   - name: volume_name
  #     mountPath: /path/to/my/secret
  # volumes:
  #   - name: volume_name
  #     secret:
  #       defaultMode: 733
  #       secretName: my_secret
  #       items:
  #       - key: my_secret.txt
  #         path: name_of_file_in_container.txt
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Storage Service
storage:
  # Enable storage provisioning
  enabled: false
  image:
    repository: supabase/storage-api
    pullPolicy: IfNotPresent
    tag: v0.46.4
  imagePullSecrets: []
  replicaCount: 1
  nameOverride: ""
  fullnameOverride: ""
  livenessProbe:
    httpGet:
      path: /status
      port: 5000
    initialDelaySeconds: 3
  readinessProbe: {}
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    type: ClusterIP
    port: 5000
  environment:
    # Override the database hostname if using external database
    # DB_HOST: DATABASE.NAMESPACE.svc.cluster.local
    DB_USER: supabase_storage_admin
    DB_PORT: 5432
    DB_DRIVER: postgres
    DB_SSL: disable  # disable, allow, prefer, require, verify-ca, verify-full
    PGOPTIONS: -c search_path=storage,public
    FILE_SIZE_LIMIT: "52428800"
    STORAGE_BACKEND: file  # file, s3
    FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    TENANT_ID: stub
    REGION: stub
    GLOBAL_S3_BUCKET: stub
    # Set variables below and secret.s3 above to enable S3 storage bucket
    # If using this chart's minio, skip the endpoint and protocol below
    # GLOBAL_S3_ENDPOINT: http://minio:9000
    # GLOBAL_S3_PROTOCOL: http
    # GLOBAL_S3_FORCE_PATH_STYLE: true
    # AWS_DEFAULT_REGION: stub
  # volumeMounts:
  #   - name: volume_name
  #     mountPath: /path/to/my/secret
  # volumes:
  #   - name: volume_name
  #     secret:
  #       defaultMode: 733
  #       secretName: my_secret
  #       items:
  #       - key: my_secret.txt
  #         path: name_of_file_in_container.txt
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  persistence:
    enabled: true
    storageClassName: "simplyblock-csi-sc"
    annotations: {}
    size: 10Gi
    accessModes:
      - ReadWriteMany
    class: ""
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}

# PgExporter Service
pgexporter:
  enabled: false
  imagePullSecrets: []
  replicaCount: 1
  nameOverride: ""
  fullnameOverride: ""
  livenessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 3
  readinessProbe: {}
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    type: ClusterIP
    port: 9187
