{{- if and .Values.storage.enabled .Values.storage.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
<<<<<<<< HEAD:src/deployment/charts/vela/templates/autoscaler/storage-pvc.yaml
  name: {{ include "vela.autoscaler.name" . }}-storage-pvc
========
  name: {{ include "vela.storage.pvcName" . }}
>>>>>>>> 171fbef0 (move rest,meta,storage out of vm):src/deployment/charts/vela/templates/storage/pvc.yaml
  labels:
    {{- include "vela.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  {{- with .Values.storage.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.storage.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
<<<<<<<< HEAD:src/deployment/charts/vela/templates/autoscaler/storage-pvc.yaml
  volumeMode: Block
========
>>>>>>>> 171fbef0 (move rest,meta,storage out of vm):src/deployment/charts/vela/templates/storage/pvc.yaml
  accessModes:
  {{- range .Values.storage.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size | quote }}
{{- end }}
