{{- if and .Values.storage.enabled .Values.storage.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vela.storage.serviceAccountName" . }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  {{- with .Values.storage.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
