{{- if .Values.storage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vela.storage.fullname" . }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  type: {{ .Values.storage.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.storage.service.port | default 5000 }}
      targetPort: {{ .Values.storage.service.port | default 5000 }}
      protocol: TCP
  selector:
    {{- include "vela.storage.selectorLabels" . | nindent 4 }}
{{- end }}
