apiVersion: stackgres.io/v1
kind: SGInstanceProfile
metadata:
  namespace: vela-services
  name: size-s
spec:
  memory: "1Gi"

---
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  namespace: vela-services
  name: database
spec:
  instances: 1
  postgres:
    version: '17'  # TODO db-version
  pods:
    persistentVolume:
      size: '5Gi'
  sgInstanceProfile: 'size-s'
