{{- if .Values.pgbouncer.enabled -}}
{{- $pgbouncerName := printf "%s-pgbouncer" (include "vela.fullname" .) -}}
{{- $pgbouncerSelectorName := printf "%s-pgbouncer" (include "vela.name" .) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $pgbouncerName }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pgbouncer.service.type }}
  ports:
    - port: {{ .Values.pgbouncer.service.port }}
      targetPort: 6432
      protocol: TCP
      name: pgbouncer
  selector:
    vm.kubevirt.io/name: {{ include "vela.db.fullname" . }}
{{- end }}
