{{- if .Values.db.enabled -}}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ include "vela.db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
spec:
  runStrategy: Always
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vela.db.selectorLabels" . | nindent 8 }}
    spec:
      domain:
        cpu:
          cores: 32 # we do resource limiting using Requests and Limits
          sockets: 2
          threads: 1
        memory:
          guest: {{ .Values.db.resources.guestMemory }}
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: datadisk # /vdb
              disk:
                bus: virtio
            - name: db-secrets # /vdc
              disk:
                bus: virtio
            - name: compose-config # /vdd
              disk:
                bus: virtio # /vde
            - name: jwt-secrets
              disk:
                bus: virtio
            - name: k8s-api-access # /vdf
              disk:
                bus: virtio
            - name: pgbouncer-config # /vdg
              disk:
                bus: virtio
            {{- if .Values.storage.enabled }}
            - name: storage-disk # /vdh
              disk:
                bus: virtio
            {{- end }}
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          limits:
            cpu: {{ .Values.db.resources.limits.cpu }}
          requests:
            cpu: {{ .Values.db.resources.requests.cpu }}
      networks:
      - name: default
        pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: manoharbrm/kubevirt:alpine-{{ .Values.db.image.tag }}
        - name: datadisk # vdb
          persistentVolumeClaim:
            claimName: {{ include "vela.db.fullname" . }}-pvc
        - name: db-secrets # vdc
          secret:
            secretName: {{ include "vela.secret.db" . }}
        - name: compose-config # vdd
          configMap:
            name: {{ include "vela.db.fullname" . }}-compose
        - name: jwt-secrets # vde
          secret:
            secretName: {{ include "vela.secret.jwt" . }}
        - name: k8s-api-access # vdf
          serviceAccount:
            serviceAccountName: {{ printf "%s-vm-config-reader" (include "vela.db.fullname" .) }}
        - name: pgbouncer-config # vdg
          configMap:
            name: {{ printf "%s-pgbouncer" (include "vela.db.fullname" .) }}
        {{- if .Values.storage.enabled }}
        - name: storage-disk # vdh
          persistentVolumeClaim:
            claimName: {{ include "vela.db.fullname" . }}-storage-pvc
        {{- end }}
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef: 
              name: "{{ include "vela.db.fullname" . }}-cloudinit-userdata"
{{- end }}
