{{- $createPVC := default true .Values.db.persistence.create -}}
{{- if and .Values.db.enabled .Values.db.persistence.enabled $createPVC -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vela.db.fullname" . }}-pvc
  labels:
    {{- include "vela.labels" . | nindent 4 }}
  {{- with .Values.db.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.db.persistence.storageClassName }}
  storageClassName: {{ .Values.db.persistence.storageClassName }}
  {{- end }}
  accessModes:
  {{- range .Values.db.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size | quote }}
{{- end }}
