{{- if .Values.rest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vela.rest.fullname" . }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
    app.kubernetes.io/component: rest
spec:
  type: {{ .Values.rest.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.rest.service.port | default 3000 }}
      targetPort: {{ .Values.rest.service.port | default 3000 }}
      protocol: TCP
  selector:
    {{- include "vela.rest.selectorLabels" . | nindent 4 }}
{{- end }}
