{{- if and .Values.rest.enabled .Values.rest.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vela.rest.serviceAccountName" . }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
    app.kubernetes.io/component: rest
  {{- with .Values.rest.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
