{{- if and .Values.db.enabled .Values.composeYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.db.fullname" . }}-compose
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  vector.yml: |
{{- .Values.vectorYaml | nindent 4 }}
  docker-compose.yml: |
{{- .Values.composeYaml | nindent 4 }}
{{- end }}
