{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "supabase.db.fullname" . }}-storage-pvc
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.storage.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.storage.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.storage.persistence.volumeMode }}
  {{- end }}
  accessModes:
  {{- range .Values.storage.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size | quote }}
{{- end }}
