{{- if .Values.db.enabled -}}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ include "supabase.db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  runStrategy: Always
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.db.selectorLabels" . | nindent 8 }}
    spec:
      domain:
        cpu:
          cores: {{ .Values.db.vcpu }}
          sockets: 1
          threads: 1
        memory:
          guest: {{ .Values.db.ram }}Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: datadisk
              disk:
                bus: virtio
            - name: storage-disk
              disk:
                bus: virtio
            - name: initdb-scripts-data
              disk:
                bus: virtio
            - name: migrations-data
              disk:
                bus: virtio
            - name: db-secrets
              disk:
                bus: virtio
            - name: compose-config
              disk:
                bus: virtio
            - name: jwt-secrets
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: {{ .Values.db.ram }}Gi
      networks:
      - name: default
        pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: manoharbrm/kubevirt:alpine-{{ .Values.db.image.tag }}-compose
        - name: datadisk
          persistentVolumeClaim:
            claimName: {{ include "supabase.db.fullname" . }}-pvc
        - name: storage-disk
          persistentVolumeClaim:
            claimName: {{ include "supabase.db.fullname" . }}-storage-pvc
        - name: initdb-scripts-data
          configMap:
            name: {{ include "supabase.db.fullname" . }}-initdb
        - name: migrations-data
          configMap:
            name: {{ include "supabase.db.fullname" . }}-migrations
        - name: db-secrets
          secret:
            secretName: {{ include "supabase.secret.db" . }}
        - name: compose-config
          configMap:
            name: {{ include "supabase.db.fullname" . }}-compose
        - name: jwt-secrets
          secret:
            secretName: {{ include "supabase.secret.jwt" . }}
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef: 
              name: "{{ include "supabase.db.fullname" . }}-cloudinit-userdata"
{{- end }}
