{{- if .Values.db.enabled -}}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ include "supabase.db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  runStrategy: Always
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.db.selectorLabels" . | nindent 8 }}
    spec:
      domain:
        cpu:
          sockets: {{ .Values.db.cpu.topology.sockets }}
          cores: {{ .Values.db.cpu.topology.cores }}
          threads: {{ .Values.db.cpu.topology.threads }}
          maxSockets: {{ .Values.db.cpu.topology.maxSockets }}
          maxCores: {{ .Values.db.cpu.topology.maxCores }}
          maxThreads: {{ .Values.db.cpu.topology.maxThreads }}
        memory:
          guest: {{ .Values.db.memory.guest }}
          maxGuest: {{ .Values.db.memory.maxGuest }}
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: datadisk
              disk:
                bus: scsi
            - name: initdb-scripts-data
              disk:
                bus: virtio
            - name: migrations-data
              disk:
                bus: virtio
            - name: db-secrets
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            cpu: {{ .Values.db.cpu.request }}
            memory: {{ .Values.db.memory.request }}
          limits:
            cpu: {{ .Values.db.cpu.limit }}
            memory: {{ .Values.db.memory.limit }}
      networks:
      - name: default
        pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: manoharbrm/kubevirt:alpine-{{ .Values.db.image.tag }}-cpu2
        - name: datadisk
          persistentVolumeClaim:
            claimName: {{ include "supabase.db.fullname" . }}-pvc
        - name: initdb-scripts-data
          configMap:
            name: {{ include "supabase.db.fullname" . }}-initdb
        - name: migrations-data
          configMap:
            name: {{ include "supabase.db.fullname" . }}-migrations
        - name: db-secrets
          secret:
            secretName: {{ include "supabase.secret.db" . }}
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef: 
              name: "{{ include "supabase.db.fullname" . }}-cloudinit-userdata"
{{- end }}
