{{- if .Values.db.enabled -}}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ include "supabase.db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  runStrategy: Always
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.db.selectorLabels" . | nindent 8 }}
    spec:
      domain:
        cpu:
          cores: 32 # we do resource limiting using Requests and Limits
          sockets: 2
          threads: 1
        memory:
          guest: {{ .Values.db.resources.limits.memory }}
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: datadisk # /vdb
              disk:
                bus: virtio
            - name: storage-disk # /vdc
              disk:
                bus: virtio
            - name: db-secrets # /vdd
              disk:
                bus: virtio
            - name: compose-config # /vde
              disk:
                bus: virtio # /vdf
            - name: jwt-secrets
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          limits:
            cpu: {{ .Values.db.resources.limits.cpu }}
          requests:
            cpu: {{ .Values.db.resources.requests.cpu }}
      networks:
      - name: default
        pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: manoharbrm/kubevirt:alpine-{{ .Values.db.image.tag }}-compose
        - name: datadisk # vdb
          persistentVolumeClaim:
            claimName: {{ include "supabase.db.fullname" . }}-pvc
        - name: storage-disk # vdc
          persistentVolumeClaim:
            claimName: {{ include "supabase.db.fullname" . }}-storage-pvc
        - name: db-secrets # vdd
          secret:
            secretName: {{ include "supabase.secret.db" . }}
        - name: compose-config # vde
          configMap:
            name: {{ include "supabase.db.fullname" . }}-compose
        - name: jwt-secrets # vdf
          secret:
            secretName: {{ include "supabase.secret.jwt" . }}
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef: 
              name: "{{ include "supabase.db.fullname" . }}-cloudinit-userdata"
{{- end }}
