{{- if .Values.autoscalerVm.enabled }}
{{- $releaseFullname := include "vela.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-rest" $releaseFullname }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rest.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.rest.service.port | default 3000 }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
{{ include "vela.autoscaler.selectorLabel" . | nindent 4 }}

---
{{- if .Values.storage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-storage" $releaseFullname }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
spec:
  type: {{ .Values.storage.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.storage.service.port | default 5000 }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
{{ include "vela.autoscaler.selectorLabel" . | nindent 4 }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-meta" $releaseFullname }}
  labels:
    {{- include "vela.labels" . | nindent 4 }}
spec:
  type: {{ .Values.meta.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.meta.service.port | default 8080 }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
{{ include "vela.autoscaler.selectorLabel" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-pgexporter" $releaseFullname }}
  labels:
    app: pgexporter
    {{- include "vela.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pgexporter.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.pgexporter.service.port | default 9187 }}
      targetPort: 9187
      protocol: TCP
      name: http
  selector:
{{ include "vela.autoscaler.selectorLabel" . | nindent 4 }}
{{- end }}
