{{- if .Values.db.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: vela-vela-rest
  labels:
    {{- include "vela.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rest.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.rest.service.port | default 3000 }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    vm.kubevirt.io/name: {{ include "vela.db.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: vela-vela-realtime
  labels:
    {{- include "vela.labels" . | nindent 4 }}
spec:
  type: {{ .Values.realtime.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.realtime.service.port | default 4000 }}
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    vm.kubevirt.io/name: {{ include "vela.db.fullname" . }}
---
{{- if .Values.storage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: vela-vela-storage
  labels:
    {{- include "vela.labels" . | nindent 4 }}
spec:
  type: {{ .Values.storage.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.storage.service.port | default 5000 }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    vm.kubevirt.io/name: {{ include "vela.db.fullname" . }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: vela-vela-meta
  labels:
    {{- include "vela.labels" . | nindent 4 }}
spec:
  type: {{ .Values.meta.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.meta.service.port | default 8080 }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    vm.kubevirt.io/name: {{ include "vela.db.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: vela-vela-pgexporter
  labels:
    app: pgexporter
    {{- include "vela.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pgexporter.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.pgexporter.service.port | default 9187 }}
      targetPort: 9187
      protocol: TCP
      name: http
  selector:
    vm.kubevirt.io/name: {{ include "vela.db.fullname" . }}
{{- end }}
