apiVersion: v1
kind: Config
clusters:
- name: talos-cluster2
  cluster:
    server: https://10.10.11.40:6443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpekNDQVRDZ0F3SUJBZ0lSQUlsZ1YwcHNNbDY3OUh3eFh0c1VEQ3d3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEV3TURjeU1EQXhNelphRncwek5URXdNRFV5TURBeApNelphTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVNyaXozWnEwcUp3SnkydUkxWWZWUm04YklWMVhhWjlZQVExU245R2NscGowK0g0WFBtcDlTcUdGYTkKanVIM1F3V2h5Z2NkcmRJYWVEOE9KSytpakRib28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGTUw2T0VkSlNmc29OQWJVbXA5eEx6dm53MDJUTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDaUlqZkYKZjNJQjIwVk9OdG44MURqOElJNVBTNURwRGUySG5Eby9VTERseEFJaEFNeGdtWW83TUlTci9RQm5sNlBnSmRseQpBTUp5OXRUck5xaE91R05lTHJ0TAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
users:
- name: admin@talos-cluster2
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoakNDQVN1Z0F3SUJBZ0lSQUtZLzNVaTZ6SkFHS0hsNEVDcXA3c2N3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEV3TURjeU1EQTBNRFJhRncweU5qRXdNRGN5TURBMApNVFJhTUNreEZ6QVZCZ05WQkFvVERuTjVjM1JsYlRwdFlYTjBaWEp6TVE0d0RBWURWUVFERXdWaFpHMXBiakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkEwaXZrM0twdWlwdEFlWDJod2Q1OFl2dVpwWnBaS1IKazNMbTFnVFVLQjF2SllqWXZGcnByb1Znckt5bXdWM0xSMnFwNzY1WjAyTUxNVFdvWTBqSlIzK2pTREJHTUE0RwpBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFqQWZCZ05WSFNNRUdEQVdnQlRDCitqaEhTVW43S0RRRzFKcWZjUzg3NThOTmt6QUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUF1TkRJaytVcmNiTEUKb21XRThrTnd5RGVwVXRjSEJvR2dHL1hWVTBSMVluMENJUUREOG9qVWppWUhtL3JkRjBHV1NZeHhxcDVDcUxSZApYK0hpL2hrUkkvZXBPdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUtYQ1AwWWh0N1JVYW9jUjl6ZE1TTzl4b3Fya21aMVlxUFgwZnJjMEdaMkFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFRFNLK1RjcW02S20wQjVmYUhCM254aSs1bWxtbGtwR1RjdWJXQk5Rb0hXOGxpTmk4V3VtdQpoV0NzcktiQlhjdEhhcW52cmxuVFl3c3hOYWhqU01sSGZ3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
contexts:
- context:
    cluster: talos-cluster2
    namespace: default
    user: admin@talos-cluster2
  name: admin@talos-cluster2
current-context: admin@talos-cluster2
