name: Check project

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install linter
      run: pip install ruff

    - name: Execute linter
      run: ruff check


  type-check:
    name: Type checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install type checker
      run: pip install mypy .

    - name: Execute type checker
      run: mypy src


  lint-charts:
    name: Lint charts
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.6.0

    - name: Lint charts
      run: ct lint --validate-maintainers=false --target-branch=${{ github.head_ref || github.ref_name }}

    - name: Create kind cluster
      uses: helm/kind-action@v1.8.0

    - name: Install charts
      run: ct install --target-branch=${{ github.head_ref || github.ref_name }} 


  test:
    name: API tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install podman and podman-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y podman podman-compose

    - name: Build and start API
      run: podman-compose -f containers/compose-ci.yml up --detach --build

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Spoof token
      id: token
      run: |
        pip install pyjwt
        echo token=$(python3 -c "import jwt; from uuid import uuid4; print(jwt.encode({'sub': str(uuid4())}, 'secret', algorithm='HS256'))") >> $GITHUB_OUTPUT

    - name: Test API
      id: test
      uses: schemathesis/action@v2
      with:
        schema: http://localhost:8000/openapi.json
        wait-for-schema: 20
        args: >-
          --header "Authorization: Bearer ${{ steps.token.outputs.token }}"

    - name: Get logs
      if: failure() && steps.test.outcome == 'failure'
      run: podman-compose -f containers/compose-ci.yml logs

    - name: Shutdown containers
      run: podman-compose -f containers/compose-ci.yml down
