name: Check project

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install linter
      run: pip install ruff

    - name: Execute linter
      run: ruff check


  format:
    name: Check format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install linter
      run: pip install ruff

    - name: Execute linter
      run: ruff format --check


  type-check:
    name: Type checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install type checker
      run: pip install mypy .

    - name: Execute type checker
      run: mypy src


  lint-charts:
    name: Lint charts
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.6.0

    - name: Lint charts
      run: ct lint --validate-maintainers=false --target-branch=${{ github.head_ref || github.ref_name }}

    - name: Create kind cluster
      uses: helm/kind-action@v1.8.0

    - name: Install charts
      run: ct install --target-branch=${{ github.head_ref || github.ref_name }} 
